config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }


  namespace :admin do
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:index, :show, :edit,:update, :destroy]

  end

  scope module: :admin do
    get 'admin' => 'homes#top', as: :admin_top
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only:[:show, :edit, :update]
    resources :tags, only: [:create, :destroy, :edit, :update]
    resources :genres, only:[:index, :show]

    get 'about' => 'homes#about'
    get 'map' => 'posts#map'
    get 'nature' => 'genres#nature'
    get 'sports' => 'genres#sports'
    get 'animal' => 'genres#animal'
    get 'sky' => 'genres#sky'
    get 'fashion' => 'genres#fashion'
    get 'meal' => 'genres#meal'
    get 'night_view' => 'genres#night_view'
    get 'military' => 'genres#military'
    get 'art' => 'genres#art'
    get 'architecture' => 'genres#architecture'
    get 'portrait' => 'genres#portrait'
    get 'bw' => 'genres#bw'
    get 'vehicle' => 'genres#vehicle'
    get 'wedding' => 'genres#wedding'
    get 'other' => 'genres#other'

    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'spot_search' => 'posts#spot_search'
    get "/posts/:id/exif" => "posts#exif", as: :exif
    get '/post/user_post/:user_id' => 'posts#user_post', as: 'user_post'


  end




end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :post
   validates :comment, presence: true, length: {in: 1..50}
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def index
    @comments= Comment.all
    @comments_page= Comment.all.page(params[:page]).per(10)
  end

  def destroy
    @comment= Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-12">
      <h2>コメント管理画面</h2>
      <table class= "table mt-5 mb-3">
        <thead>
          <tr>
            <th>コメントユーザー</th>
            <th>投稿時間</th>
            <th>コメント</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
          <tbody>
          <% if @comments.present? %>
            <% @comments.each do |comment| %>
            <tr>
              <td>
                <%= comment.user.name %>
              </td>
              <td>
                <%= comment.created_at.strftime('%Y/%m/%d') %>
              </td>
              <td>
                <%= comment.comment %>
              </td>
              <td>
                <%= link_to "削除する",admin_comment_path(comment.id), method: :delete, data: {confirm: "削除しますか？"} %>
              </td>
            </tr>
            <% end %>
          <% else %>
            <p>コメントがありません。</p>
          <% end %>
        </tbody>
      </table>
      <%= paginate @comments_page %>
    </div>
  </div>
</div>