config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }


  namespace :admin do
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:index, :show, :edit,:update, :destroy]

  end

  scope module: :admin do
    get 'admin' => 'homes#top', as: :admin_top
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only:[:show, :edit, :update]
    resources :tags, only: [:create, :destroy, :edit, :update]
    resources :genres, only:[:index, :show]

    get 'about' => 'homes#about'
    get 'map' => 'posts#map'
    get 'nature' => 'genres#nature'
    get 'sports' => 'genres#sports'
    get 'animal' => 'genres#animal'
    get 'sky' => 'genres#sky'
    get 'fashion' => 'genres#fashion'
    get 'meal' => 'genres#meal'
    get 'night_view' => 'genres#night_view'
    get 'military' => 'genres#military'
    get 'art' => 'genres#art'
    get 'architecture' => 'genres#architecture'
    get 'portrait' => 'genres#portrait'
    get 'bw' => 'genres#bw'
    get 'vehicle' => 'genres#vehicle'
    get 'wedding' => 'genres#wedding'
    get 'other' => 'genres#other'

    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'spot_search' => 'posts#spot_search'
    get "/posts/:id/exif" => "posts#exif", as: :exif
    get '/post/user_post/:user_id' => 'posts#user_post', as: 'user_post'


  end




end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genres, dependent: :destroy
  has_many_attached :image

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre= Genre.new
    @genres= Genre.all
  end

  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h3>ジャンル編集</h3>

    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
      <div class="form-inline p-2">
        <label>ジャンル名</label>
        <%= f.text_field :name, class: "form-control m-3" %>
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
    <% end %>

app/views/admin/genres/index.html.erb
   <h3>ジャンル一覧・追加</h3>

    <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <%= f.label :genre, "ジャンル名" %>
      <%= f.text_field :name %>
      <%= f.submit '新規登録', class: 'btn btn-success'%>
    <% end %>

    <table class="table">
      <thead>
          <th class="table-active">ジャンル</th>
          <th class="table-active"></th>
      </thead>
      <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= genre.name %>
          </td>
          <td>
            <%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm" %>
          </td>
        </tr>
      </tbody>
      <% end %>