config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }


  namespace :admin do
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:index, :show, :edit,:update, :destroy]

  end

  scope module: :admin do
    get 'admin' => 'homes#top', as: :admin_top
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only:[:show, :edit, :update]
    resources :tags, only: [:create, :destroy, :edit, :update]
    resources :genres, only:[:index, :show]

    get 'about' => 'homes#about'
    get 'map' => 'posts#map'
    get 'nature' => 'genres#nature'
    get 'sports' => 'genres#sports'
    get 'animal' => 'genres#animal'
    get 'sky' => 'genres#sky'
    get 'fashion' => 'genres#fashion'
    get 'meal' => 'genres#meal'
    get 'night_view' => 'genres#night_view'
    get 'military' => 'genres#military'
    get 'art' => 'genres#art'
    get 'architecture' => 'genres#architecture'
    get 'portrait' => 'genres#portrait'
    get 'bw' => 'genres#bw'
    get 'vehicle' => 'genres#vehicle'
    get 'wedding' => 'genres#wedding'
    get 'other' => 'genres#other'

    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'spot_search' => 'posts#spot_search'
    get "/posts/:id/exif" => "posts#exif", as: :exif
    get '/post/user_post/:user_id' => 'posts#user_post', as: 'user_post'


  end




end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts,through: :post_tags
  validates :name, uniqueness: true, presence: true

  def self.search(keyword)
    where('name LIKE ?' , "%#{keyword}%")
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tag= Tag.new
    @tags= Tag.all
    @tags_page= Tag.all.page(params[:page]).per(10)
  end

  def create
    @tag= Tag.new(tag_params)
    @tag.save!
    redirect_to request.referer
  end

  def edit
    @tag= Tag.find(params[:id])

  end

  def update
    @tag= Tag.find(params[:id])
    @tag.update(tag_params)
    redirect_to admin_tags_path
  end

  def destroy
    @tag= Tag.find(params[:id])
    @tag.destroy
    redirect_to request.referer
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :post_id)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-12">
      <h2 class= "mb-5">管理者タグ編集</h2>
      <%= form_with model: @tag, url: admin_tag_path(@tag.id), method: :patch do |f| %>
        <%= f.label :name, "タグ:" %>
        <%= f.text_field :name %><br>
        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
 <div class="container text-center">
  <h3>タグ管理画面</h3>
  <div class="row">
    <div class="col-12">
      <%= form_with model: @tag, url: admin_tags_path, local: true do |f| %>
      <table class= "mt-3 mb-3">
        <tr>
          <th>登録するタグ</th>
          <td><%= f.text_field :name, class: "ml-3" %></td>
          <td><%= f.submit 'タグ登録', class: "btn btn-sm btn-success ml-3" %></td>
        </tr>
      </table>
    <% end %>
    </div>
  </div>

   <div class="row">
      <div class="col-12">
        <table class= "table">
          <thead>
            <tr>
              <th>タグ</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td>
                   <%= tag.name %>
                </td>
                <td>
                  <%= link_to "編集する",edit_admin_tag_path(tag.id) %>
                </td>
                <td>
                  <%= link_to "削除する",admin_tag_path(tag.id), method: :delete, data: {confirm: "削除しますか？"} %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @tags_page %>
      </div>
    </div>
 </div>