config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
  }


  namespace :admin do
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:index, :show, :edit,:update, :destroy]

  end

  scope module: :admin do
    get 'admin' => 'homes#top', as: :admin_top
  end

  scope module: :public do
    root to: 'homes#top'
    resources :users, only:[:show, :edit, :update]
    resources :tags, only: [:create, :destroy, :edit, :update]
    resources :genres, only:[:index, :show]

    get 'about' => 'homes#about'
    get 'map' => 'posts#map'
    get 'nature' => 'genres#nature'
    get 'sports' => 'genres#sports'
    get 'animal' => 'genres#animal'
    get 'sky' => 'genres#sky'
    get 'fashion' => 'genres#fashion'
    get 'meal' => 'genres#meal'
    get 'night_view' => 'genres#night_view'
    get 'military' => 'genres#military'
    get 'art' => 'genres#art'
    get 'architecture' => 'genres#architecture'
    get 'portrait' => 'genres#portrait'
    get 'bw' => 'genres#bw'
    get 'vehicle' => 'genres#vehicle'
    get 'wedding' => 'genres#wedding'
    get 'other' => 'genres#other'

    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'posts#search'
    get 'spot_search' => 'posts#spot_search'
    get "/posts/:id/exif" => "posts#exif", as: :exif
    get '/post/user_post/:user_id' => 'posts#user_post', as: 'user_post'


  end




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true , uniqueness: true , length: { in: 2..20}
  validates :email, presence: true
  validates :introduction, length: {maximum: 50}

  def self.guest
    find_or_create_by!(email: 'guest_signin328@gmail.com',name: 'guestuser') do |user|
      user.password= SecureRandom.urlsafe_base64
      user.name= "guestuser"
    end
  end

  def ensure_guest_user
    @user= User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーは編集画面へ遷移できません。'
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
      image
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


  def index
    @users_page= User.all.page(params[:page]).per(10)
  end

  def show
    @user= User.find(params[:id])
  end

  def edit
    @user= User.find(params[:id])
  end

  def update
    @user= User.find(params[:id])
    @user.update(user_params)
    redirect_to request.referer
  end

  private

  def user_params
    params.require(:user).permit(:image, :name, :introduction)
  end

  def ensure_current_user
    @user= User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user)
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user= User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました'
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-12">
      <h2 class= "mb-5">管理者ユーザー編集</h2>
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
        <%= f.label :image, "ユーザー画像" %>
        <%= f.file_field :image, accept: "image/*" %><br>
        <%= f.label :name, "ユーザー名:" %>
        <%= f.text_field :name %><br>
        <%= f.label :email, "メールアドレス:" %>
        <%= f.text_field :email %><br>
        <%= f.label :introduction, "紹介文:" %>
        <%= f.text_field :introduction %><br>
        <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-12">
      <h2>ユーザー管理画面</h2>
      <table class= "table mt-5 mb-3">
        <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>ユーザー名</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "詳細を見る", admin_user_path(user.id) %>
            </td>
            <td>
              <%= link_to "編集する",edit_admin_user_path(user.id) %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @users_page %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-12 mt-3 mb-5">
      <h4><%= @user.name %>さんの管理ページ</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @user.get_profile_image(200,200) %>
    </div>
    <div class="col-md-8">
      ユーザー名:
      <%= @user.name %><br>
      メールアドレス:
      <%= @user.email %><br>
      自己紹介:
      <%= @user.introduction %><br>
    </div>
  </div>
</div>